Dock pob bug fix
DiscoveryGC/FLHook pull request #128
Opened 2020-09-16 09:59 UTC by dd84ai

2020-09-16 13:12 UTC, dd84ai commented
wait a second, it has not solved problems yet

2020-09-16 13:56 UTC, dd84ai commented
now it is working regardless of which plugin is loaded first. done,

2020-09-27 23:38 UTC, dsyalex requested changes
please squash your commits and add a reasonable description

2020-09-28 05:15 UTC, dd84ai commented
Resolved

2020-10-03 08:33 UTC, dd84ai commented
Discovered it can be coded possibly easier than I did

2020-10-03 11:55 UTC, dd84ai commented
Remade removing not optimized trash ;b

2020-10-11 23:34 UTC, dsyalex commented on Source/FLHookPluginSDK/headers/plugin.h
> +	bool iAnswer;
```suggestion
	bool bAnswer;
```

2020-10-11 23:34 UTC, dsyalex commented on Plugins/Public/base_plugin/Main.cpp
> +			returncode = SKIPPLUGINS;
```suggestion
```

2020-10-11 23:35 UTC, dsyalex reviewed
What about the -0.55 check on POBs? Players shouldn't be able to dock if their reputation with the base's affiliation is too close to hostile right?

2020-10-12 07:51 UTC, dd84ai commented
> What about the -0.55 check on POBs? Players shouldn't be able to dock if their reputation with the base's affiliation is too close to hostile right?

This restriction is supposed to be applied only during defensemode == 2, when base allows docking rights from player reputation
Perhaps sometime later, someone could fix it. It is not a really important feature anyway, too overspecialized.
There would be needed changes in IsDockingAllowed function

2020-10-12 07:53 UTC, dd84ai commented on Source/FLHookPluginSDK/headers/plugin.h
> +	bool iAnswer;
applied

2020-10-12 07:54 UTC, dd84ai commented on Plugins/Public/base_plugin/Main.cpp
> +			returncode = SKIPPLUGINS;
applied

2020-11-22 04:30 UTC, dsyalex approved these changes

2020-11-22 04:30 UTC, merged