shop fix
DiscoveryGC/FLHook pull request #129
Opened 2020-09-16 13:21 UTC by dd84ai

We discussed it before, this is what you suggested Alex.

2020-09-27 23:38 UTC, dsyalex requested changes
let's add the brackets to be clear what should be happening here, also fix the description to describe the change please

2020-09-28 06:06 UTC, dd84ai commented
Added description and brackets

2020-10-11 23:37 UTC, dsyalex commented
`base->market_items[gbi.iGoodID].min_stock > base->market_items[gbi.iGoodID].quantity - count`
there is still ambiguity here, both `>` and `-` in use without brackets

2020-10-12 07:35 UTC, dd84ai commented
I get it. in case if the result of > operation can be casted into int and becoming 0 - 1 value used for subtracting operation.

2020-10-12 07:38 UTC, dd84ai commented
fixed

2020-11-22 04:18 UTC, dsyalex reviewed
Looks good but we now need to also take care of the check on line 1671

2020-11-22 07:26 UTC, dd84ai commented
> Looks good but we now need to also take care of the check on line 1671

fixed

2020-11-23 02:41 UTC, dsyalex approved these changes

2020-11-23 02:41 UTC, merged