feat(base): + 1 cargo storage to every +1 base level
DiscoveryGC/FLHook pull request #145
Opened 2021-01-22 18:05 UTC by dd84ai

increase of cargo storage maximum in proportion to base level
maximum cargo storage += cargo module size * (base level - 1)

Approval: https://discord.com/channels/444137064439742474/698718138145046538/800912934321520662
![image](https://user-images.githubusercontent.com/20555918/105528003-02f25900-5d17-11eb-9859-7c35240b7b79.png)

2021-02-05 13:25 UTC, dd84ai commented
Tests:
Base level 1: 30'000 space
Base level 2: 70'000 space
Base level 3: 110'000 space
Filling base with 109900 commodity
Attempt to sell 50 units to base, successful
Attempt to sell 250 units to base, unsuccessful

All tests have been passed

2021-02-06 11:15 UTC, dsyalex reviewed
I'm a bit worried about whether people knew this was an entire extra storage module rather than a single extra unit or a single extra thousand units or something.

2021-02-06 11:53 UTC, dd84ai commented
> I'm a bit worried about whether people knew this was an entire extra storage module rather than a single extra unit or a single extra thousand units or something.

Never realized that it can be interpreted in any way like that. I thought it looks obvious enough.

2021-02-06 11:59 UTC, dsyalex requested changes
let's come back to this pending interpretation check in discord

2021-02-06 17:24 UTC, dsyalex commented
Darkwind and Haste are coming up with an alternative proposal that conflicts with this idea, plus another staff team has raised concerns about this and have injected a lot of uncertainty into the idea of trusting #game-mechanics-votes.

2021-02-06 17:24 UTC, closed without merging