feat(set_admin): new groups, chasepull and aicontrol
DiscoveryGC/FLHook pull request #146
Opened 2021-01-25 18:37 UTC by dd84ai

feat(set_admin): adds two new subgroups to set admin command
setadmin PlayerName chasepull, which allows
```
chase
pull
```
setadmin PlayerName aicontrol, which allows
```
aidestroy
aicancel
aifollow
aicome
aifleet
fleetlist
```

2021-01-25 18:41 UTC, dd84ai commented
btw, tested in game that everything works fine:
chasepull admin is not able to do aicreate
and aiecreate admin is not able to chasepull
and both can't beam

2021-01-27 14:18 UTC, dd84ai commented
Do not merge, I have a problem

2021-01-27 18:28 UTC, dd84ai commented
Solved everything

2021-02-05 18:21 UTC, dd84ai commented
Performed tests:
]
1) setadmin Player cloak,chasepull, 
it can cloak, it can chase, but can't setcash and can't beam Erie and can't basecreate
2) setadmin Player aicontrol,beamkill
it can't cloak, it can aicreate, it can't setcash, it can beam
3) setadmin Player bases,beamkill
it can basecreate, it can beamkill, it can't cloak, it can't setcash, it can't use .generateid
4) setadmin Player superadmin
it can use generated, it can cloak, it can chasepull, it can basecreate, it can pvecontroller status
5) setadmin Player plugins,beamkill
it can pvecontroller status, it can't cloak, it can beam

All tests have been passed

2021-02-06 11:27 UTC, dsyalex requested changes
reee indentation and code duplication. otherwise looks fine :)

2021-02-06 11:27 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
> +		RIGHT_CHECK(RIGHT_SUPERADMIN)
this is actually harmless and should probably not even be an admincmd - actually I would question why it's an FLHook command at all, and not some out-of-game utility. But this is the existing check so okay 👍

2021-02-06 11:27 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
> +		RIGHT_CHECK(RIGHT_SUPERADMIN)
this command... does nothing???

2021-02-06 11:27 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
> +		RIGHT_CHECK(RIGHT_SUPERADMIN)
this is actually harmless and I question whether it should be admin-restricted, though I also wonder whether it should really be an FLHook command at all.

2021-02-06 11:27 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
> +	RIGHT_CHECK(RIGHT_SUPERADMIN)
missing indentation

2021-02-06 11:27 UTC, dsyalex commented on Plugins/Public/npc_control/Main.cpp
> +#define RIGHT_CHECK(a) if(!(cmds->rights & a)) { cmds->Print(L"ERR No permission\n"); return; }
should we just define this thing straight into FLHook core itself?

2021-02-06 12:37 UTC, dsyalex requested changes
I have a feeling those bitwise-style checks in RIGHT_CHECK will fail against RIGHT_SUPERADMIN

If you consider it as 8 bits for this example:
Let's say you have rights 00010000
RIGHT_SUPERADMIN in our example is 11111111
check is `!(cmds->rights & RIGHT_SUPERADMIN)` to find unauthorised access
00010000 & 11111111
result: 00010000
!00010000
result: false
I think it breaks

2021-02-06 13:03 UTC, dsyalex requested changes

2021-02-06 13:03 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
can be removed

2021-02-06 13:03 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
same here

2021-02-06 13:03 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
and here

2021-02-06 13:03 UTC, dsyalex commented on Plugins/Public/npc_control/Main.cpp
> +#define RIGHT_CHECK(a) if(!(cmds->rights & a)) { cmds->Print(L"ERR No permission\n"); return; }
A: no, they can be a bit different

2021-02-06 13:28 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
nope

2021-02-06 13:28 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
nope

2021-02-06 13:28 UTC, dsyalex commented on Plugins/Public/alley/PlayerRestrictions.cpp
>  		HKPLAYERINFO adminPlyr;
nope

2021-02-06 13:41 UTC, dsyalex approved these changes

2021-02-06 13:42 UTC, merged