New functionality: POB restricted commodity list
DiscoveryGC/FLHook pull request #175
Opened 2023-01-08 14:47 UTC by Aingar

Requested by Haste

New functionality - forbidden commodity list on POBs. Blocks attempts to sell a given cargo on a POB regardless if it's already on the manifest, base administrator status and so on. Allows to purchase the commodity from the base if it had it onboard due to admin intervention or had it stashed before this change went live.

new .cfg file: base_forbidden_cargo.cfg
structure:
[forbidden_commodities]

commodity_name = commodity_passengers
commodity_name = commodity_cardamine

2023-01-09 02:10 UTC, dsyalex requested changes
This looks like it won't work for 2+ commodities - see inline

2023-01-09 08:46 UTC, Aingar commented on Plugins/Public/base_plugin/Main.cpp
> +						cargoID = CreateID(ini.get_value_string(0));
Should be just fine I think, but yeah, no reason to fragment the code that can be a single line.
Submitting changes.

2023-01-22 05:54 UTC, dsyalex requested changes
Still looks broken

2023-01-22 18:39 UTC, dsyalex approved these changes

2023-01-22 18:39 UTC, merged