Converting project to VS2022
DiscoveryGC/FLHook pull request #210
Opened 2023-05-15 13:44 UTC by Aingar

Old bad, new better.
Also made all plugin projects with boost dependencies have the /dependencies folder added to external dependencies. Why weren't they already?

Plausible performance increase due to using newer compiler.

Test server is currently running VS2022 generated DLLs without any issues.

2023-06-04 23:05 UTC, dsyalex commented on Plugins/Public/alley/alley.vcxproj
> +      <AdditionalIncludeDirectories>A:\FLHookAingar\Dependencies;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
ditto

2023-06-04 23:05 UTC, dsyalex commented on Plugins/Public/base_plugin/Base Plugin.vc14.vcxproj
> +      <AdditionalIncludeDirectories>A:\FLHookAingar\Dependencies;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
ditto

2023-06-04 23:05 UTC, dsyalex commented on Plugins/Public/playercntl_plugin/Player Control Plugin.vc14.vcxproj
> +      <AdditionalIncludeDirectories>A:\FLHookAingar\Dependencies;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
ditto

2023-06-04 23:11 UTC, Aingar commented on Plugins/Public/JSONBuddy/JSONBuddy.vcxproj
> +      <AdditionalIncludeDirectories>A:\FLHookAingar\Dependencies;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
Whoops. Also that's one of my main hard drives, I'm a rebel.

2023-06-04 23:18 UTC, dsyalex requested changes
needs fixing to work for people who don't write their FLHook to A: drive and aren't called Aingar :P

2023-06-07 22:53 UTC, merged

2023-06-20 16:25 UTC, dsyalex commented
Cf private PR 1